services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - middleware

  ai-server:
    build: ./ai-server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - middleware

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - ai-server
    networks:
      - middleware

volumes:
  mongo_data:

networks:
  middleware:
    driver: bridge
      


