services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - middleware
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8443:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    networks:
      - middleware

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    volumes:
      - ./ollama-volumes:/app/volumes
    networks:
      - middleware

  ai-server:
    build: ./ai-server
    container_name: ai-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - ollama
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      OLLAMA_HOST: http://ollama:11434
    networks:
      - middleware

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - ai-server
    networks:
      - middleware

volumes:
  mongo_data:

networks:
  middleware:
    driver: bridge
      


